#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SKIP_FEATURE_CACHE=1 PARALLEL=2 CASE_PARALLEL=4 \
RUN_BASELINE=0 \
RUN_RANGE_QUALITY_MATRIX=1 \
RUN_RANGE_REGIME_THRESHOLD_MATRIX=0 \
RUN_TREND_MATRIX=0 \
RUN_TREND_NEXT_STEP_MATRIX=0 \
RUN_TREND_ENTRY_THRESHOLD_MATRIX=0 \
RUN_HOLD_EXIT_MATRIX=0 \
RUN_TREND_ENTRY_DIAGNOSTICS=0 \
RUN_FOLD_BREAKDOWN=0 \
RUN_LOSS_FOLD_REVIEW=0 \
RUN_LOSS_FOLD_TRADE_DETAIL=0 \
RUN_LOSS_HOLD_THRESHOLD=0 \
RUN_BUILD_AGGREGATE_REPORT=0 \
RUN_BUILD_TREND_NEXT_STEP_REPORT=0 \
RUN_BUILD_TREND_ENTRY_THRESHOLD_REPORT=0 \
RUN_BUILD_HOLD_EXIT_REPORT=0 \
RUN_BUILD_RANGE_QUALITY_REPORT=1 \
OUT_DIR=data/validation/core_expansion/range_htf_sr_run \
./scripts/core_expansion_tuning.sh

exit

SKIP_FEATURE_CACHE=1 PARALLEL=2 CASE_PARALLEL=4 \
RUN_BASELINE=0 \
RUN_RANGE_QUALITY_MATRIX=1 \
RUN_RANGE_REGIME_THRESHOLD_MATRIX=0 \
RUN_TREND_MATRIX=0 \
RUN_TREND_NEXT_STEP_MATRIX=0 \
RUN_TREND_ENTRY_THRESHOLD_MATRIX=0 \
RUN_HOLD_EXIT_MATRIX=0 \
RUN_TREND_ENTRY_DIAGNOSTICS=0 \
RUN_FOLD_BREAKDOWN=0 \
RUN_LOSS_FOLD_REVIEW=0 \
RUN_LOSS_FOLD_TRADE_DETAIL=0 \
RUN_LOSS_HOLD_THRESHOLD=0 \
RUN_BUILD_AGGREGATE_REPORT=0 \
RUN_BUILD_TREND_NEXT_STEP_REPORT=0 \
RUN_BUILD_TREND_ENTRY_THRESHOLD_REPORT=0 \
RUN_BUILD_HOLD_EXIT_REPORT=0 \
RUN_BUILD_RANGE_QUALITY_REPORT=1 \
OUT_DIR=data/validation/core_expansion/range_sr_run \
./scripts/core_expansion_tuning.sh
