from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    DUPLICATE_CLIENT_ORDER_ID = "DUPLICATE_CLIENT_ORDER_ID"
    STALE_SIGNAL = "STALE_SIGNAL"
    GATING_BLOCKED = "GATING_BLOCKED"
    RUNTIME_TRADING_DISABLED = "RUNTIME_TRADING_DISABLED"
    RUNTIME_EMERGENCY_STOP = "RUNTIME_EMERGENCY_STOP"
    RUNTIME_STATE_INVALID = "RUNTIME_STATE_INVALID"
    RATE_LIMIT = "RATE_LIMIT"
    NETWORK_ERROR = "NETWORK_ERROR"
    TIMEOUT = "TIMEOUT"
    SERVER_ERROR = "SERVER_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
